name: Cypress CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [14.10.0]

    steps:
    - uses: actions/checkout@v2

    - name: set many environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        REACT_APP_BACKEND: http://localhost:8000/api

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run e2e

